//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminPanel.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Education
    {
        public long Id { get; set; }
        public long ProfileId { get; set; }
        public string DegreeTitle { get; set; }
        public string School { get; set; }
        public string PassingYear { get; set; }
        public Nullable<int> TotalMarks { get; set; }
        public Nullable<int> MarksObtained { get; set; }
        public Nullable<int> Percentage { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    }
}
